# Generated by Django 4.1 on 2022-09-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
